### ISSUE TITLE
Buggy visualization of high-res images

### ISSUE THREAD

**Issue by arincbulgur** [haochenheheda/segment-anything-annotator#10]
Annotator app doesn't load images correctly if their resolution is higher than the app resolution. It shows them cropped and rotated. Would be great if the app resizes the image to the app resolution and converts annotations back to the original image resolution after finding them in the app resolution.

**Comment by haochenheheda** [comment]
Thanks for your feedback! I'll add the size adaptation latter. And also you could zoom in/out the image with `left ctrl` + `mouse wheel`.

**Comment by arincbulgur** [comment]
Thank you for your suggestion. Yeah, then I guess there is no cropping happening. But, it doesn't resolve the orientation issue. For some reason, app rotates really high-res images, generally 90 or 180 degrees. This is not happening with low res images. Would you have any guess where it might be happening? If you can guide me, maybe I can look at it and fix it.

**Comment by haochenheheda** [comment]
I added `scale` before draw images on the canvas to display large images.

https://github.com/haochenheheda/segment-anything-annotator/blob/b0c3288ee6b83e8d0bed2f22da8a287c985dfe48/annnotator.py#L623-L625 

You may rewrite this part to add `rotation` if the issue still exists.
