### ISSUE TITLE
bug:Manual polygon annotation cannot be propagated to other frames

### ISSUE THREAD

**Issue by 1374839016** [haochenheheda/segment-anything-annotator#13]
The annotation results can be propagated to other frames using segment anything assisted annotation, but manual polygon annotation cannot be propagated to other frames.

**Comment by haochenheheda** [comment]
I just tried, and it worked. Please make sure the polygons are selected and added to memory before using propagating.

**Comment by haochenheheda** [comment]
Oh, maybe you forget to switch to Edit mode after manually create polygon.

**Comment by Rui-R** [comment]
oh i see , we should manually assign an id to this object, or it won't added to memory because its id is none.

**Comment by haochenheheda** [comment]
Thanks for your feedbacks. 
I'll fix the ID assignment issue in manual polygon mode.
