### ISSUE TITLE
功能完善建议

### ISSUE THREAD

**Issue by CalvinSMU** [haochenheheda/segment-anything-annotator#14]
因为项目需要已经部署标注了一百多种图片，感觉非常棒，觉得还可以补充几个功能：

1. 和官网的demo相比，还可以增加负样本的点作为输入，这样标注出来的效果会更好，SAM的代码里是集成了正负样本的point prompt，我觉得可以增加一个模式（Negative/Positive Point Prompt）
2. 在编辑标注的时候，可不可以手动删除某些不需要的点（不过labelme也不支持这个功能）
3. 可以增加一个窗口，显示所有导入的图片名称和是否标注的状态

**Comment by haochenheheda** [comment]
1. 现在左键是positive point，右键是negative point
2. 3. 这两个功能开发起来稍微麻烦一点，我有时间争取搞一下。 对于删除不需要的点，目前可以先reduce point，再手动调整
