### ISSUE TITLE
error

### ISSUE THREAD

**Issue by ym666888** [haochenheheda/segment-anything-annotator#15]
已经安装了segment_anything,报错 no module named 'segment_anything

**Comment by ym666888** [comment]
您好，请问为什么这个程序打出来的json标签里面imageData为空。我拿labelme软件打的标签imagedata都有很长的一段图片字符串信息

**Comment by haochenheheda** [comment]
搞定了

**Comment by ym666888** [comment]
This JSON file (C:/Users/32869/Desktop/fenge\IMG_6629.json) may be incompatible with current labelme. version in file: 1.0.0, current version: 5.2.0
Traceback (most recent call last):
  File "e:\anaconda\lib\site-packages\labelme\app.py", line 1113, in fileSelectionChanged
    self.loadFile(filename)
  File "e:\anaconda\lib\site-packages\labelme\app.py", line 1545, in loadFile
    self.loadLabels(self.labelFile.shapes)
  File "e:\anaconda\lib\site-packages\labelme\app.py", line 1230, in loadLabels
    shape.flags.update(flags)
TypeError: 'NoneType' object is not iterable
您好还是打不开呀，标注后拿labelme这个软件脚本打开还是报错，这个版本显示1.0.0（这个得修改成labelme的版本号），labelme是5.2.0的。还有labelme打开标注后的图片闪退，显示TypeError: 'NoneType' object is not iterable

**Comment by ym666888** [comment]
您好，还有个小建议是最好标签labels可以自己写几个固定一下，要不每次都还得重新输入标签，打扰您了
