### ISSUE TITLE
Object that create by manually doesn't have group ID.

### ISSUE THREAD

**Issue by seungtaek94** [haochenheheda/segment-anything-annotator#17]
Object that create by manually doesn't have group ID.

![image](https://github.com/haochenheheda/segment-anything-annotator/assets/56434476/84f7bbf5-57d6-4184-90cf-f739d9684373)

**Comment by haochenheheda** [comment]
![image](https://github.com/haochenheheda/segment-anything-annotator/assets/19390123/84dd1db5-b063-4b13-948b-b1fdbbf9a6b6)
