### ISSUE TITLE
无法保存右键负标注部分为背景

### ISSUE THREAD

**Issue by bitongtong** [haochenheheda/segment-anything-annotator#21]
![QQ截图20230621151443](https://github.com/haochenheheda/segment-anything-annotator/assets/28655326/9833a5f4-b66f-4d2f-a627-8cf7c38b56bc)
![QQ截图20230621151731](https://github.com/haochenheheda/segment-anything-annotator/assets/28655326/d8b891ad-60ea-4248-8edd-b3937f8eec21)

如图所示，请问如何保存目标物中的空洞为背景呢？

**Comment by bitongtong** [comment]
能否把内部空白区域像labelme一样设置为0:_background_ 呢？

**Comment by haochenheheda** [comment]
您好，我是后处理的时候把叠加的部分处理成背景的。目前在软件里面没有实现，你可以先accept，然后手动修改中间洞的label到0:background
