### ISSUE TITLE
[Feature Request] Adjust image size in the polygon-editing window

### ISSUE THREAD

**Issue by fclof** [haochenheheda/segment-anything-annotator#22]
![6AABFF04-1B1F-4d2b-AF48-95D494313963](https://github.com/haochenheheda/segment-anything-annotator/assets/43123988/d986dec7-c630-46f1-b8e8-0c3da7614225)
As shown in the image above. When labeling a large image (in my case, a 2000x2000 px image), the polygon-editing window seems to only display the left-top part (about 700x1000 px) of the orginal image. This limitation really slows down the labeling progress, because I have to crop my image into many 700x700 images and then stitch them together.

Is there a way to make the window larger?

**Comment by haochenheheda** [comment]
You can use ctrl+mouse wheel to zoom in/out.
