### ISSUE TITLE
功能完善建议

### ISSUE THREAD

**Issue by 1215232494** [haochenheheda/segment-anything-annotator#6]
体验了一下，先给作者点个赞！
之前一直用的labelme，提几个比较常用的功能需求
1. json 格式，若能与原始官方格式保持一致，用户量应该不会少，否则考虑到后续的数据处理会劝退很多人
"version": "5.0.0",
  "flags": {},
  "shapes": [
    {
      "label": "",
      "points":[ ]
      "group_id": ,
      "shape_type": "",
      "flags": {}
    }
  ],
  "imagePath": "",
  "imageData":
  "imageHeight": ,
  "imageWidth": 
} 

2.一些快捷键：
ctrl+z撤销上一步操作；
切换上/下张图片（官方快捷键a/d）；
切换图片自动保存json；

**Comment by haochenheheda** [comment]
感谢建议，我最近会弄一下这几个点

**Comment by haochenheheda** [comment]
现在格式已经是labelme的了。然后切换图片快捷键是b/n（a/d已经占用了），切换图片会自动保存json
撤销的功能我试了下，涉及到修改label的缓存，目前没有跟sam新加的功能兼容，后续我会再调一下
