### ISSUE TITLE
疑问

### ISSUE THREAD

**Issue by leichaoyang** [haochenheheda/segment-anything-annotator#8]
可以加载labelme标注好的数据吗

**Comment by haochenheheda** [comment]
目前还不行，这周我会把标注文件格式转成labelme的格式

**Comment by haochenheheda** [comment]
现在可以啦

**Comment by leichaoyang** [comment]
谢谢



---原始邮件---
发件人: "haochen ***@***.***&gt;
发送时间: 2023年5月1日(周一) 晚上8:28
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [haochenheheda/segment-anything-annotator] 疑问 (Issue #8)




 
现在可以啦
